apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-microservice
  template:
    metadata:
      labels:
        app: python-microservice
    spec:
      containers:
      - name: python-microservice
        image: 881892164822.dkr.ecr.ap-south-1.amazonaws.com/micro-app
        ports:
        - containerPort: 5000

