apiVersion: v1
kind: Service
metadata:
  name: python-microservice-service
spec:
  type: LoadBalancer
  selector:
    app: python-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
